### ISSUE TITLE
build reset() not working.

### ISSUE THREAD

**Issue by tm3s** [jackfranklin/test-data-bot#934]
Greetings team.
I'm using "@jackfranklin/test-data-bot": "^2.0.0", with node V16.

I'm trying to reset my builder sequence but I'm getting the following error:
```
Property 'reset' does not exist on type '(buildTimeConfig?: BuildTimeConfig
```

I'm not sure if I might be missing anything.

**Comment by jackfranklin** [comment]
Hello,

Thanks for the report! Please could you share the entire code of your test
so we can more easily reproduce the issue?

Thanks!

**Comment by tm3s** [comment]
Any luck/alternative I can try @jackfranklin ?

**Comment by jackfranklin** [comment]
Unfortunately not so far. Can you see if you run this code if it works? I am wondering if it is an error with the TypeScript definitions, rather than the actual source code.

**Comment by tm3s** [comment]
So what I did is I gave the variable a any type to deal with the Type error.
But when I run the code it gives me the error `reset is not a function...`

**Comment by jackfranklin** [comment]
Can I double check, since updating to v2.0.0 you have done an npm install to make sure you are up to date?

This is hard to debug as I cannot see anything obviously wrong. Can you try recreating it on https://codesandbox.io/ or similar?

**Comment by jackfranklin** [comment]
Closing due to not enough info. Please create a new issue or report back if you still have problems. Thanks
